### ISSUE TITLE
A question. Is it safe to play Clear Sky with turned up switch_distance?

### ISSUE THREAD

**Issue by ChuckoKokos** [Decane/SRP-Lite#1]
Is it? I'm wondering if high switch_distance can cause events to break.
EDIT: I didn't mean to post this in SRP-Lite, sorry.

**Comment by Decane** [comment]
Not sure. I've never tried playing through the entire game that way. Some scripted squad assaults might begin earlier than they would otherwise, like the Freedom assault on the mercenaries at the farm in the Dark Valley, but I can't think of any situation where a high switch_distance is likely to outright break the game.

If you decide to try it, please let me know how it goes. A high switch_distance will yield a lower overall frame-rate, but with less stutter from NPCs switching online, as any loaded NPCs will switch online as soon as you load a save. You'd still get stutter whenever new NPCs spawn on the same map as you, though, so it's not a magic bullet.
